apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: hack-stack10
  name: hack-stack10
spec:
  type: NodePort
  ports:
  - name: "trader"
    port: 9080
    targetPort: 9080
  - name: "stock-quote"
    port: 9081
    targetPort: 9081
  - name: "loyalty"
    port: 9082
    targetPort: 9082
  - name: "notification"
    port: 9083
    targetPort: 9083
  selector:
    io.kompose.service: hack-stack10
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: hack-stack10
  name: hack-stack10
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: hack-stack10
    spec:
      containers:
      - env:
        - name: LOYALTY_HOST
          value: localhost
        - name: QUOTE_HOST
          value: localhost
        - name: ZCEE_URL
          value: https://129.40.117.225:9443
        - name: ZCEE_USER
          value: HACKR10
        - name: ZCEE_PASS
          value: HACKR10
        - name: ZCEE_BASE_PATH
          value: /HACKR10
        image: cc-z-hack.icp:8500/cc-z-hack/trader-node
        name: trader
        ports:
        - containerPort: 9080
        resources: {}
      - env:
        - name: QUANDL_KEY
          value: _2VFhkQ446andCSWu2Mi
        image: cc-z-hack.icp:8500/cc-z-hack/stock-quote
        name: stock-quote
        ports:
        - containerPort: 9081
        resources: {}
      - env:
        - name: FUNCTIONS_API_KEY
          value: 41b6f490-81e6-4ccf-994c-5b3334bd2228:pbMFtcT1PhkAvPltem1YotwNKqGb3uSw0b0A40XJD8vOQRymXqOm3a3osZwRyDJR
        - name: FUNCTIONS_URL
          value: hhttps://openwhisk.ng.bluemix.net/api/v1/namespaces/Patrick.Buoniconti%40ibm.com_dev/actions/cc-z-hack/PatrickSequence
        - name: MQ_HOST
          value: 129.40.117.225
        - name: MQ_PORT
          value: "1414"
        - name: MQ_QM
          value: MQZL
        - name: MQ_QUEUE_NAME
          value: HACKR10
        image: cc-z-hack.icp:8500/cc-z-hack/notification
        name: notification
        ports:
        - containerPort: 9083
        resources: {}
      - env:
        - name: MQ_HOST
          value: 129.40.117.225
        - name: MQ_PORT
          value: "1414"
        - name: MQ_QM
          value: MQZL
        - name: MQ_QUEUE_NAME
          value: HACKR10
        image: cc-z-hack.icp:8500/cc-z-hack/loyalty
        name: loyalty
        ports:
        - containerPort: 9082
        resources: {}
      restartPolicy: Always
      nodeSelector:
        beta.kubernetes.io/arch: s390x
status: {}
