apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: hack-stack
  name: hack-stack
spec:
  type: NodePort
  ports:
  - name: "trader"
    port: 9080
    targetPort: 9080
  - name: "stock-quote"
    port: 9081
    targetPort: 9081
  - name: "loyalty"
    port: 9082
    targetPort: 9082
  - name: "notification"
    port: 9083
    targetPort: 9083
  selector:
    io.kompose.service: hack-stack
status:
  loadBalancer: {}
