apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: stock-quote
  name: stock-quote
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: stock-quote
    spec:
      containers:
      - env:
        - name: QUANDL_KEY
          value: _2VFhkQ446andCSWu2Mi
        image: cc-z-hack.icp:8500/cc-z-hack/stock-quote
        name: stock-quote
        ports:
        - containerPort: 9081
        resources: {}
      restartPolicy: Always
status: {}
