apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: trader
  name: trader
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: trader
    spec:
      containers:
      - env:
        - name: LOYALTY_HOST
          value: host.docker.internal
        - name: QUOTE_HOST
          value: host.docker.internal
        - name: ZCEE_PASS
          value: fredpwd
        - name: ZCEE_URL
          value: https://129.40.117.225:9443
        - name: ZCEE_USER
          value: Fred
        image: cc-z-hack.icp:8500/cc-z-hack/trader
        name: trader
        ports:
        - containerPort: 9080
        resources: {}
      restartPolicy: Always
status: {}
